# Generated by Django 4.1.4 on 2022-12-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolshed',
            old_name='shed',
            new_name='tool',
        ),
    ]
